openapi: 3.0.0
info:
  title: Student API
  version: 1.0.0
paths:
  /students:
    post:
      operationId: createStudent  # Specify the generated method name
      summary: Create a new student
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudentCreateRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentCreateResponse'

  /students/{studentId}:
    get:
      operationId: getStudentById  # Specify the generated method name
      summary: Get a student by ID
      parameters:
        - name: studentId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetStudentByIdResponse'

components:
  schemas:
    StudentId:
      type: string
    StudentGrade:
      type: string
    StudentCreateRequest:
      type: object
      properties:
        name:
          type: string
        grade:
          $ref: '#/components/schemas/StudentGrade'
        mobile:
          type: string
          pattern: '^\d{10}$'  # the pattern for mobile numbers (10 digits)
        school:
          type: string
      required:
        - name
        - grade
        - mobile
        - school
    StudentCreateResponse:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/StudentId'
        name:
          type: string
        grade:
          $ref: '#/components/schemas/StudentGrade'
        mobile:
          type: string
        school:
          type: string
        status:
          type: string
          enum:
            - PENDING_REGISTRATION
            - REGISTERED
            - UNREGISTERED
    GetStudentByIdResponse:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/StudentId'
        name:
          type: string
        grade:
          $ref: '#/components/schemas/StudentGrade'
        mobile:
          type: string
        school:
          type: string
        status:
          type: string
          enum:
            - PENDING_REGISTRATION
            - REGISTERED
            - UNREGISTERED

#Error responses
    ErrorResponse:
      description: "An array of detail error codes, and messages, and URLs to documentation to help remediation."
      type: "object"
      additionalProperties: false
      properties:
        Errors:
          items:
            $ref: "#/components/schemas/Error"
          type: "array"
          minItems: 1
      required:
        - "Errors"
    Error:
      type: "object"
      additionalProperties: false
      properties:
        Code:
          description: "Low level textual error code, e.g., Field.Missing"
          type: "string"
        Message:
          description: "A description of the error that occurred. "
          type: "string"
          minLength: 1
          maxLength: 500
      required:
        - "Code"
        - "Message"
      minProperties: 1
