openapi: 3.0.0
info:
  title: Payment API
  version: 1.0.0
paths:
  /reports/{paymentId}:
    post:
      operationId: getPaymentReport  # Specify the generated method name
      summary: Get the report for a payment
      parameters:
        - name: paymentId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPaymentReportByPaymentIdResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    GetPaymentReportByPaymentIdResponse:
      type: object
      properties:
        transactionDateTime: #payment initiated datetime
          type: string
        studentId:
          type: string
        studentName:
          type: string
        transactionReference: #this is the paymentId
          type: string
        maskedCardNo:
          type: string
        cardType:
          type: string
        transactionAmount:
          type: number

#Error responses
    ErrorResponse:
      description: "An array of detail error codes, and messages, and URLs to documentation to help remediation."
      type: "object"
      additionalProperties: false
      properties:
        Errors:
          items:
            $ref: "#/components/schemas/Error"
          type: "array"
          minItems: 1
      required:
        - "Errors"
    Error:
      type: "object"
      additionalProperties: false
      properties:
        Code:
          description: "Low level textual error code, e.g., Field.Missing"
          type: "string"
        Message:
          description: "A description of the error that occurred. "
          type: "string"
          minLength: 1
          maxLength: 500
      required:
        - "Code"
        - "Message"
      minProperties: 1
