CREATE TABLE IF NOT EXISTS student(
    id VARCHAR(20) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    grade VARCHAR(10) NOT NULL,
    mobile VARCHAR(20) NOT NULL,
    school VARCHAR(255) NOT NULL
);
